### ISSUE TITLE
Renaming levelnames

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#111]
- thinking about renaming class names like easylevel1(12, 292, 1) into candles (12, 292, 1) directly

**Comment by shoc71** [comment]
should make addressing these levels easier and knowing their spawn and characteristics and avoid having two lists for tracking which levels go where

We'll have that discussion when more than 30 levels have been tested, fixed, organized, and ready to be published.

**Comment by slysnivy** [comment]
The naming of the level won't matter too much. I'll let you decide if you want to include level id in the text file containing level information as well. In the text file, level id is important to determine order, otherwise the order of the levels is dependent on the order the levels are put in the text file. Also is the space in between the level name "candles" and the class parameters "(12, 292, 1)" significant in any way?

**Comment by shoc71** [comment]
Yes. The class parameters are responsible for both the spawning and calling of the relevant class. I suggested renaming the classes because the order of the levels is what I can best describe currently as random in terms of difficulty (with the exception of the tutorial levels). There is no good order for the levels currently, that takes into account the difficulty of the levels in a properly ascending order. Once we have 'enough' (<30) levels, we then can decide on the order and make it a global constant list, and then organize them into proper sets.

**Comment by slysnivy** [comment]
I believe a dictionary for level_id was made previously in v.0.2.5 and as discussed with Memory. This is improved upon in the more recent updates as well (post v.0.2.5) . Furthermore, simply including a lone number in the text file is enough to distinguish level order despite the order it's presented in the text file. Also, the renaming the class names is fine, I only asked about writing the class like Candles(12, 292, 1) compared to Candles (12, 292, 1), with a space.
