### ISSUE TITLE
Levels repeat after completion sometimes

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#204]
not sure if this is a py or txt problem but I will investigate to let you know.

**Comment by shoc71** [comment]
there is no repetition in the txt file which makes wonder why this is happening in the py file

**Comment by slysnivy** [comment]
It's likely a python issue where the victory if statement in dsn_level PlayLevel conflicts with the victory if statement in main (for statistics). 
Since they're mainly determined by pygame.time, I'm theorizing that it's random which if statement goes first. More specifically in main.py, line 38's if else or line 51's scene.update.
To solve this problem, main.py's victory if else statements can be moved to dsn_levels victory statement in the PlayLevel class.

**Comment by slysnivy** [comment]
This issue was fixed (likely) in dsn_levels #222 and main #223
